version: '3.8'

services:
  web:
    build: .
    container_name: nutriscore_prediction
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data  # Volume pour sauvegarder les données de prédiction
    environment:
      - DATA_PATH=/data/requests  # Chemin du dossier de sauvegarde des données dans le conteneur
    command: flask run --host=0.0.0.0 --port=5000

volumes:
  data:
    driver: local
